-- Schema base para migracao do banco reserva_escolar_v2 para Supabase/PostgreSQL.
-- Mantem alta compatibilidade com a API PHP atual.

begin;

create table if not exists public.schools (
    id integer generated by default as identity primary key,
    school_name varchar(150) not null,
    school_code varchar(50) not null unique,
    password varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists public.resource_categories (
    id integer generated by default as identity primary key,
    name varchar(80) not null unique
);

create table if not exists public.users (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    name varchar(120) not null,
    email varchar(120) not null,
    password varchar(255) not null,
    api_token varchar(64),
    api_token_expires_at timestamp,
    role varchar(20) not null check (role in ('technician', 'teacher')),
    active smallint not null default 1 check (active in (0, 1)),
    created_at timestamp not null default current_timestamp,
    constraint unique_user_email_per_school unique (school_id, email),
    constraint uniq_users_api_token unique (api_token)
);

create table if not exists public.class_groups (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    name varchar(20) not null,
    active smallint not null default 1 check (active in (0, 1)),
    created_at timestamp not null default current_timestamp,
    constraint unique_class_group_per_school unique (school_id, name)
);

create table if not exists public.subjects (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    name varchar(100) not null,
    active smallint not null default 1 check (active in (0, 1)),
    created_at timestamp not null default current_timestamp,
    constraint unique_subject_per_school unique (school_id, name)
);

create table if not exists public.lesson_slots (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    lesson_number integer not null,
    label varchar(30) not null,
    start_time time,
    end_time time,
    active smallint not null default 1 check (active in (0, 1)),
    created_at timestamp not null default current_timestamp,
    constraint unique_lesson_per_school unique (school_id, lesson_number)
);

create table if not exists public.resources (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    category_id integer not null references public.resource_categories(id),
    name varchar(150) not null,
    active smallint not null default 1 check (active in (0, 1)),
    created_at timestamp not null default current_timestamp,
    constraint unique_resource_per_school unique (school_id, name)
);

create table if not exists public.bookings (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    resource_id integer not null references public.resources(id) on delete cascade,
    user_id integer not null references public.users(id) on delete cascade,
    class_group_id integer not null references public.class_groups(id),
    subject_id integer not null references public.subjects(id),
    booking_date date not null,
    purpose varchar(255),
    status varchar(20) default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled')),
    created_at timestamp not null default current_timestamp,
    cancelled_at timestamp,
    completed_at timestamp,
    completion_feedback text,
    completed_by_user_id integer references public.users(id),
    cancelled_by_user_id integer references public.users(id)
);

create table if not exists public.booking_lessons (
    id integer generated by default as identity primary key,
    booking_id integer not null references public.bookings(id) on delete cascade,
    lesson_slot_id integer not null references public.lesson_slots(id),
    constraint unique_booking_lesson unique (booking_id, lesson_slot_id)
);

create table if not exists public.notifications (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    user_id integer not null references public.users(id) on delete cascade,
    type varchar(60) not null,
    title varchar(150) not null,
    message text not null,
    booking_id integer references public.bookings(id) on delete cascade,
    metadata_json text,
    read_at timestamp,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_bookings_school_id on public.bookings (school_id);
create index if not exists idx_bookings_resource_id on public.bookings (resource_id);
create index if not exists idx_bookings_user_id on public.bookings (user_id);
create index if not exists idx_bookings_class_group_id on public.bookings (class_group_id);
create index if not exists idx_bookings_subject_id on public.bookings (subject_id);
create index if not exists idx_bookings_cancelled_by_user_id on public.bookings (cancelled_by_user_id);
create index if not exists idx_bookings_completed_by_user_id on public.bookings (completed_by_user_id);
create index if not exists idx_booking_lessons_lesson_slot_id on public.booking_lessons (lesson_slot_id);
create index if not exists idx_notifications_school_user_created_at on public.notifications (school_id, user_id, created_at desc);
create index if not exists idx_notifications_user_read_at on public.notifications (user_id, read_at);
create index if not exists idx_users_school_id on public.users (school_id);
create index if not exists idx_resources_category_id on public.resources (category_id);
create index if not exists idx_resources_school_id on public.resources (school_id);

-- Seeds conhecidos da base atual.
insert into public.resource_categories (id, name)
values
    (1, 'chromebooks'),
    (2, 'audiovisual'),
    (3, 'espacos')
on conflict (id) do update set name = excluded.name;

-- Ajusta as sequences caso os IDs acima ou imports manuais avancem a numeracao.
select setval(
    pg_get_serial_sequence('public.schools', 'id'),
    greatest((select coalesce(max(id), 1) from public.schools), 1),
    (select coalesce(max(id), 0) > 0 from public.schools)
);
select setval(
    pg_get_serial_sequence('public.resource_categories', 'id'),
    greatest((select coalesce(max(id), 1) from public.resource_categories), 1),
    (select coalesce(max(id), 0) > 0 from public.resource_categories)
);
select setval(
    pg_get_serial_sequence('public.users', 'id'),
    greatest((select coalesce(max(id), 1) from public.users), 1),
    (select coalesce(max(id), 0) > 0 from public.users)
);
select setval(
    pg_get_serial_sequence('public.class_groups', 'id'),
    greatest((select coalesce(max(id), 1) from public.class_groups), 1),
    (select coalesce(max(id), 0) > 0 from public.class_groups)
);
select setval(
    pg_get_serial_sequence('public.subjects', 'id'),
    greatest((select coalesce(max(id), 1) from public.subjects), 1),
    (select coalesce(max(id), 0) > 0 from public.subjects)
);
select setval(
    pg_get_serial_sequence('public.lesson_slots', 'id'),
    greatest((select coalesce(max(id), 1) from public.lesson_slots), 1),
    (select coalesce(max(id), 0) > 0 from public.lesson_slots)
);
select setval(
    pg_get_serial_sequence('public.resources', 'id'),
    greatest((select coalesce(max(id), 1) from public.resources), 1),
    (select coalesce(max(id), 0) > 0 from public.resources)
);
select setval(
    pg_get_serial_sequence('public.bookings', 'id'),
    greatest((select coalesce(max(id), 1) from public.bookings), 1),
    (select coalesce(max(id), 0) > 0 from public.bookings)
);
select setval(
    pg_get_serial_sequence('public.booking_lessons', 'id'),
    greatest((select coalesce(max(id), 1) from public.booking_lessons), 1),
    (select coalesce(max(id), 0) > 0 from public.booking_lessons)
);

commit;
