begin;

create table if not exists public.notifications (
    id integer generated by default as identity primary key,
    school_id integer not null references public.schools(id) on delete cascade,
    user_id integer not null references public.users(id) on delete cascade,
    type varchar(60) not null,
    title varchar(150) not null,
    message text not null,
    booking_id integer references public.bookings(id) on delete cascade,
    metadata_json text,
    read_at timestamp,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_notifications_school_user_created_at
    on public.notifications (school_id, user_id, created_at desc);

create index if not exists idx_notifications_user_read_at
    on public.notifications (user_id, read_at);

commit;
